In [6]:
import numpy as np

print(np.__version__)

#below is a 0 dimensional array
# array = np.array("A")

# array = np.array(['a', 'b', 'c'])
#above is a 1 dimensional

array = np.array([[['a', 'b', 'c'], ['d', 'e', 'f'],['g', 'h', 'i']], 
                  [['j', 'k', 'l'], ['m', 'n', 'o'],['p', 'q', 'r']], 
                  [['s', 't', 'u'], ['v', 'w', 'x'],['y', 'z', ' ']]])

# 3 would require another 3 sets of array from the pre existing ones
#all arrays must be homogenous 
# if three sets then 3 sets on all arrays


print(array.ndim)
print(array.shape)
# gives shape layers, rows, and columns 
print(array[0,1,0])

word = array[2,0,0] + array[1,1,2] + array[2,0,0]
print(word)

#now slicing
array2 = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8], 
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

print(array2[::2])
#this is row selection

#now we move into column selection
print('')
print(array2[:, ::-1])
# first is row, then column number
# : be used to access all rows

#now we combine row and column selection
print('')
print(array2[2:, 2:])

#now we do scalar arithmetic

array3 = np.array([1, 2, 3])

print('')
print(array3 + 1)
print(array3 - 4)
print(array3 * 10)
print(array3 / 4)
print(array3 ** 2)

#Vectorized math functions
array4 = np.array([1, 2, 3])

print(" ")
print(np.sqrt(array4))
print(np.round(array4))
#print(np.pi) would give us pi

radii = np.array([1, 2, 3])
areaOfCircle = np.pi * (radii ** 2)

print(areaOfCircle)

#Element-wise arithmetic 
arrays1 = np.array([1, 2, 3])
arrays2 = np.array([4, 5, 6])

print(arrays1 + arrays2)
print(arrays1 - arrays2)
print(arrays1 * arrays2)
print(arrays1 / arrays2)
print(arrays1 ** arrays2)

#Comparison Operators
scores = np.array([91, 55, 100, 73, 82, 64])

print(scores == 100)
scores[scores < 60] = 0
print(scores)


2.2.6
3
(3, 3, 3)
d
sos
[[ 1  2  3  4]
 [ 9 10 11 12]]

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]

[[11 12]
 [15 16]]

[2 3 4]
[-3 -2 -1]
[10 20 30]
[0.25 0.5  0.75]
[1 4 9]
 
[1.         1.41421356 1.73205081]
[1 2 3]
[ 3.14159265 12.56637061 28.27433388]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]
[False False  True False False False]
[ 91   0 100  73  82  64]


In [11]:
#Broadcasting allows Numpy to preform operations on arrays
#With different shapes 

broad1 = np.array([[1, 2, 3, 4]])
broad2 = np.array([[1], [2], [3], [4]])
# shapes of the array must match or be 1


print(" ")
print(broad1.shape)
print(broad2.shape)

print(broad1 * broad2)

table = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
multTable = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])

print(table.shape)
print(multTable.shape)

print(table * multTable)





 
(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [15]:
#Aggregate Function allow us to summarize data and then return values
aggArray = np.array([[1, 2, 3, 4, 5], 
                  [6, 7, 8, 9, 10]])

print(" ")
print(np.sum(aggArray))
print(np.mean(aggArray))
print(np.std(aggArray))
print(np.var(aggArray))
print(np.min(aggArray))
print(np.max(aggArray))
print(np.argmin(aggArray))
#position of the min value
print(np.argmax(aggArray))
#postion of max value
print(np.sum(aggArray, axis= 0))
#sum of columns
print(np.sum(aggArray, axis=1))
#sum of rows




 
55
5.5
2.8722813232690143
8.25
1
10
0
9
[ 7  9 11 13 15]
[15 40]
