In [ ]:
import numpy as np

print(np.__version__)

#below is a 0 dimensional array
# array = np.array("A")

# array = np.array(['a', 'b', 'c'])
#above is a 1 dimensional

array = np.array([[['a', 'b', 'c'], ['d', 'e', 'f'],['g', 'h', 'i']], 
                  [['j', 'k', 'l'], ['m', 'n', 'o'],['p', 'q', 'r']], 
                  [['s', 't', 'u'], ['v', 'w', 'x'],['y', 'z', ' ']]])

# 3 would require another 3 sets of array from the pre existing ones
#all arrays must be homogenous 
# if three sets then 3 sets on all arrays


print(array.ndim)
print(array.shape)
# gives shape layers, rows, and columns 
print(array[0,1,0])

word = array[2,0,0] + array[1,1,2] + array[2,0,0]
print(word)

#now slicing
array2 = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8], 
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

print(array2[::2])
#this is row selection

#now we move into column selection
print('')
print(array2[:, ::-1])
# first is row, then column number
# : be used to access all rows

#now we combine row and column selection
print('')
print(array2[2:, 2:])

#now we do scalar arithmetic

array3 = np.array([1, 2, 3])


2.2.6
3
(3, 3, 3)
d
sos
[[ 1  2  3  4]
 [ 9 10 11 12]]

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]

[[11 12]
 [15 16]]


array([[['a', 'b', 'c'],
        ['d', 'e', 'f'],
        ['g', 'h', 'i']],

       [['j', 'k', 'l'],
        ['m', 'n', 'o'],
        ['p', 'q', 'r']],

       [['s', 't', 'u'],
        ['v', 'w', 'x'],
        ['y', 'z', ' ']]], dtype='<U1')